### PR TITLE
Let user decide whether to call watch() or fetch()

### PR DESCRIPTION
**Pull request by hoducha**

### CODE REVIEW

**Comment by roman01la** [comment]
Hi @hoducha 

According to Horizon's Collection API `fetch` doesn't create subscription to updates, it just returns a snapshot of data. So it's basically a one time request. That is not the purpose of this library.

If you want to use other methods from Collection API, you can always get an instance of Horizon client from React's context and use it directly, like this:

``` jsx
class MyComponent extends Component {
      static contextTypes = {
        hz: PropTypes.func
      }
      constructor() {
        super();
        this.state = { data: [] }
      }
      componentDidMount() {
        this.context.hz('items').fetch().subscribe((data) => this.setState({ data }));
      }
     // ...
}
```

**Comment by hoducha** [comment]
Hi @roman01la,

Thank you for clarifying it. I made the change because in some cases I need just one-time request. If that is not the purpose of the library then please skip it.

**Comment by roman01la** [comment]
@hoducha You can build a component, on top of `connect`, which will pass Horizon instance from context via props. This way you can avoid accessing context in every component where you need Horizon instance.

**Comment by hoducha** [comment]
Yeah, that's exactly what I'm thinking. Thank you!

**Pull request closed without merging**
