### PR TITLE
Upgrade horizon to 2.0, fixes #5

### LINKED ISSUE #5: Upgrade horizon to 2.0
Horizon 2.0 is out http://horizon.io/blog/horizon-2/

### PR DESCRIPTION
**Pull request by gutenye**
USAGE

```
$ npm install react-hz @horizon/client
```

### CODE REVIEW

**Comment by roman01la** [comment]
@gutenye Thanks! Why did you move Horizon client into peer deps?

**Comment by gutenye** [comment]
horizon-client shoule be independent, both 1.x and 2.x works with react-horizon. Move it into peer deps, so that I can choose the version freely. And when there is new version on horizon-client, I only need to update horizon-client, instead of updating react-horizon.

**Comment by roman01la** [comment]
ok, this makes sense. My only concern is that the tests are failing, because Horizon client is not installed automatically anymore. Do you think you could take care of this issue?

**Comment by roman01la** [comment]
Closing in favor of #8

**Pull request closed without merging**
